import React, { useState } from 'react';

export default function ReportExport({ partId, contextId, ecrId }) {
  const [exporting, setExporting] = useState(false);
  const [bomReport, setBomReport] = useState(null);
  const token = () => localStorage.getItem('token') || '';

  const exportCSV = () => {
    setExporting(true);
    const url = `/api/v1/plm/reports/part-list?contextId=${contextId || 1}&format=csv`;
    fetch(url, { headers: { Authorization: `Bearer ${token()}` } })
      .then(r => r.blob()).then(blob => {
        const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
        a.download = `parts-export-${new Date().toISOString().slice(0,10)}.csv`; a.click();
      }).finally(() => setExporting(false));
  };

  const generateBomReport = () => {
    if (!partId) return;
    setExporting(true);
    fetch(`/api/v1/plm/reports/bom?partId=${partId}&format=pdf`, { headers: { Authorization: `Bearer ${token()}` } })
      .then(r => r.json()).then(r => { if (r.success) setBomReport(r.data); })
      .finally(() => setExporting(false));
  };

  const printBomReport = () => {
    const w = window.open('', '_blank');
    if (!bomReport) return;
    const lines = bomReport.bomLines || [];
    w.document.write(`<html><head><title>BOM Report - ${bomReport.partNumber}</title>
      <style>body{font-family:Arial,sans-serif;margin:20px;color:#1a202c}h1{font-size:18px;margin:0 0 4px}h2{font-size:14px;color:#64748b;margin:0 0 16px}table{width:100%;border-collapse:collapse;font-size:12px}th{text-align:left;padding:6px 8px;border-bottom:2px solid #e2e8f0;background:#f8fafc}td{padding:5px 8px;border-bottom:1px solid #e2e8f0}.footer{margin-top:16px;font-size:10px;color:#94a3b8}</style></head><body>
      <h1>BOM Report: ${bomReport.partNumber} - ${bomReport.partName}</h1>
      <h2>Revision: ${bomReport.partRevision} | Generated: ${new Date().toLocaleString()} | Lines: ${lines.length}</h2>
      <table><thead><tr><th>Level</th><th>Part Number</th><th>Name</th><th>Revision</th><th>Qty</th><th>Unit</th><th>Find No</th></tr></thead><tbody>
      ${lines.map(l => `<tr><td>${l.bomLevel}</td><td>${l.partNumber}</td><td>${l.partName}</td><td>${l.partRevision}</td><td>${l.quantity}</td><td>${l.unit||'EA'}</td><td>${l.findNumber||''}</td></tr>`).join('')}
      </tbody></table><div class="footer">Generated by Windchill PLM</div></body></html>`);
    w.document.close(); w.print();
  };

  return (
    <div style={{ padding: 0 }}>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}>
        <button onClick={exportCSV} disabled={exporting} className="btn-primary btn-sm">
          {exporting ? '...' : '📥 Export Parts CSV'}
        </button>
        {partId && (
          <button onClick={generateBomReport} disabled={exporting} className="btn-primary btn-sm">
            {exporting ? '...' : '📋 BOM Report'}
          </button>
        )}
      </div>

      {bomReport && (
        <div style={{ border: '1px solid var(--wc-border)', borderRadius: 8, padding: 12, marginTop: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <div>
              <strong>{bomReport.partNumber}</strong> — {bomReport.partName} (Rev {bomReport.partRevision})
              <span style={{ fontSize: 12, color: 'var(--wc-text-secondary)', marginLeft: 8 }}>{bomReport.bomLines?.length || 0} lines</span>
            </div>
            <button onClick={printBomReport} className="btn-primary btn-sm">🖨️ Print / PDF</button>
          </div>
          <div style={{ overflowX: 'auto', maxHeight: 400, overflowY: 'auto' }}>
            <table className="ss-table" style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
              <thead><tr><th style={th}>Lvl</th><th style={th}>Part Number</th><th style={th}>Name</th><th style={th}>Rev</th><th style={th}>Qty</th><th style={th}>Find No</th></tr></thead>
              <tbody>
                {(bomReport.bomLines || []).map((l, i) => (
                  <tr key={i}><td style={td}>{l.bomLevel}</td><td style={{...td, fontFamily:'monospace', fontSize:11}}>{l.partNumber}</td><td style={td}>{l.partName}</td><td style={td}>{l.partRevision}</td><td style={td}>{l.quantity} {l.unit||'EA'}</td><td style={td}>{l.findNumber||''}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

const th = { textAlign: 'left', padding: '5px 8px', borderBottom: '2px solid var(--wc-border)', fontSize: 10, textTransform: 'uppercase', color: 'var(--wc-text-secondary)', background: 'var(--wc-bg-hover)' };
const td = { padding: '4px 8px', borderBottom: '1px solid var(--wc-border)' };
