CREATE TABLE IF NOT EXISTS work_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    promotion_request_id BIGINT NOT NULL,
    context_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    assignee_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    due_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    completed_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    version BIGINT DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_wi_pr (promotion_request_id),
    INDEX idx_wi_assignee (assignee_user_id),
    INDEX idx_wi_status (status),
    CONSTRAINT fk_wi_promotion_request FOREIGN KEY (promotion_request_id) REFERENCES promotion_requests(id),
    CONSTRAINT fk_wi_part FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT fk_wi_context FOREIGN KEY (context_id) REFERENCES plm_contexts(id)
) ENGINE=InnoDB;
